"""``python -m bastion.tools --docs`` renders docs/TOOLS.md from the registry;
``--sudoers-apt [SYSTEMD_RUN_BIN]`` renders the apt block of deploy/sudoers.bastion."""

from __future__ import annotations

import json
import sys
from typing import Any

from bastion.tools import sorted_registry
from bastion.tools._context import ToolContext, get_context, set_context


def render_docs() -> str:
    # Plans that embed executor config (certbot email) render placeholders in docs.
    previous = get_context()
    set_context(ToolContext(postgres_dsn="<postgres_dsn>", certbot_email="<certbot_email>"))
    try:
        return _render_docs()
    finally:
        set_context(previous)


def _render_docs() -> str:
    lines = [
        "# Tools",
        "",
        "_Generated by `python -m bastion.tools --docs`. Do not edit by hand._",
        "",
        "Every action Bastion can take is one of the named, typed tools below.",
        "There is no generic command runner. Risk colours in the CLI:",
        "read = green, write = yellow, admin = red.",
        "",
        "| Tool | Risk | Approval | Roles | Summary |",
        "|---|---|---|---|---|",
    ]
    for spec in sorted_registry():
        approve = "yes" if spec.approve else "no"
        summary = spec.description.split(". ")[0].rstrip(".")
        lines.append(
            f"| `{spec.name}` | {spec.risk} | {approve} | {', '.join(spec.roles)} | {summary} |"
        )
    lines.append("")
    for spec in sorted_registry():
        lines.append(f"## `{spec.name}`")
        lines.append("")
        lines.append(spec.description)
        lines.append("")
        lines.append(f"- **Risk:** {spec.risk}")
        lines.append(f"- **Needs approval:** {'yes' if spec.approve else 'no'}")
        lines.append(f"- **Roles:** {', '.join(spec.roles)}")
        if spec.virtual:
            lines.append("- **Virtual:** handled by the CLI, never executed on the server")
        if spec.verify_with:
            lines.append(f"- **Verified after run with:** `{spec.verify_with}`")
        props = spec.input_schema().get("properties", {})
        required = set(spec.input_schema().get("required", []))
        if props:
            lines.append("- **Arguments:**")
            for pname, prop in props.items():
                desc = prop.get("description", "")
                typ = _type_of(prop)
                req = "required" if pname in required else f"default `{prop.get('default')!r}`"
                lines.append(f"  - `{pname}` ({typ}, {req}) {desc}".rstrip())
        example = _example_args(spec.input_schema())
        lines.append("- **Plan:**")
        lines.append("")
        lines.append("  ```")
        # Render the template directly (skipping live-host validators) so the
        # generated document is identical on every machine.
        plan = spec.plan_fn(**example) if spec.plan_fn else spec.plan(example)
        for pl in plan.splitlines():
            lines.append(f"  {pl}")
        lines.append("  ```")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _type_of(prop: dict[str, Any]) -> str:
    if "enum" in prop:
        return "enum: " + ", ".join(str(v) for v in prop["enum"])
    return str(prop.get("type", "any"))


def _example_args(schema: dict[str, Any]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    props = schema.get("properties", {})
    assert isinstance(props, dict)
    for pname, prop in props.items():
        if "default" in prop:
            out[pname] = prop["default"]
        elif "enum" in prop:
            out[pname] = prop["enum"][0]
        elif prop.get("type") == "integer":
            out[pname] = int(prop.get("minimum", 1))
        elif pname == "domain":
            out[pname] = "app.example.com"
        elif pname == "question":
            out[pname] = "Which service do you mean?"
        else:
            out[pname] = "example"
    return out


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if "--docs" in args:
        sys.stdout.write(render_docs())
        return 0
    if "--json" in args:
        sys.stdout.write(json.dumps([s.describe() for s in sorted_registry()], indent=2) + "\n")
        return 0
    if "--sudoers-apt" in args:
        from bastion.tools.packages import DEFAULT_SYSTEMD_RUN_BIN, render_sudoers_apt

        idx = args.index("--sudoers-apt")
        binary = args[idx + 1] if len(args) > idx + 1 else DEFAULT_SYSTEMD_RUN_BIN
        sys.stdout.write(render_sudoers_apt(binary) + "\n")
        return 0
    sys.stderr.write("usage: python -m bastion.tools --docs | --json | --sudoers-apt [BIN]\n")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
