#!/usr/bin/env bash
# Bastion executor installer (server side).
#
#   curl -fsSL https://raw.githubusercontent.com/itsrajverma/bastion/main/scripts/install.sh | sudo bash
#
# Idempotent: re-running upgrades the package and refreshes the unit/sudoers
# files but never rotates an existing token or overwrites an edited config.
#
# Environment overrides:
#   BASTION_PACKAGE   pip spec to install (default: "bastion-sre[executor]");
#                     e.g. "/path/to/checkout[executor]" for development.
#   BASTION_BIND      bind address (default 127.0.0.1:8710). Non-loopback binds
#                     are refused by the executor unless you also edit the config.
set -euo pipefail

BASTION_USER="bastion"
VENV="/opt/bastion"
CONFIG_DIR="/etc/bastion"
CONFIG="${CONFIG_DIR}/config.yaml"
LOG_DIR="/var/log/bastion"
UNIT="/etc/systemd/system/bastion-executor.service"
SUDOERS="/etc/sudoers.d/bastion"
PACKAGE="${BASTION_PACKAGE:-bastion-sre[executor]}"
BIND="${BASTION_BIND:-127.0.0.1:8710}"

say()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

[[ "$(id -u)" -eq 0 ]] || die "run as root (sudo bash install.sh)"
command -v systemctl >/dev/null || die "systemd is required"
command -v python3 >/dev/null || die "python3 (>= 3.10) is required"
python3 - <<'PY' || die "python3 >= 3.10 is required"
import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)
PY

# --- user ------------------------------------------------------------------------
if ! id -u "${BASTION_USER}" >/dev/null 2>&1; then
  say "creating system user ${BASTION_USER} (nologin)"
  useradd --system --shell /usr/sbin/nologin --home-dir /nonexistent --no-create-home "${BASTION_USER}"
else
  say "user ${BASTION_USER} exists"
fi

# --- directories ------------------------------------------------------------------
install -d -m 0750 -o root -g "${BASTION_USER}" "${CONFIG_DIR}"
install -d -m 0750 -o "${BASTION_USER}" -g "${BASTION_USER}" "${LOG_DIR}"

# --- virtualenv + package -----------------------------------------------------------
if [[ ! -x "${VENV}/bin/python" ]]; then
  say "creating virtualenv at ${VENV}"
  python3 -m venv "${VENV}"
fi
say "installing ${PACKAGE}"
"${VENV}/bin/pip" install --quiet --upgrade pip
"${VENV}/bin/pip" install --quiet --upgrade "${PACKAGE}"
[[ -x "${VENV}/bin/bastion-executor" ]] || die "bastion-executor entry point missing after install"
chown -R root:root "${VENV}"
chmod -R a+rX "${VENV}"

# --- config (never rotate an existing token) ------------------------------------------
TOKEN=""
if [[ -f "${CONFIG}" ]]; then
  say "config exists at ${CONFIG}; leaving it untouched"
else
  TOKEN="$("${VENV}/bin/python" -c 'import secrets; print(secrets.token_hex(32))')"
  say "writing ${CONFIG} (enabled_risks: [read])"
  cat > "${CONFIG}" <<EOF
# Bastion executor configuration.
# enabled_risks: [read] is the safe default. Add 'write' and/or 'admin' to allow
# approval-gated actions. Tokens: one per person, role = viewer|operator|admin.
bind: ${BIND}
enabled_risks: [read]
tokens:
  admin:
    token: "${TOKEN}"
    role: admin
postgres_dsn: null
certbot_email: null
audit_path: ${LOG_DIR}/audit.jsonl
EOF
fi
chown root:"${BASTION_USER}" "${CONFIG}"
chmod 0640 "${CONFIG}"

# --- sudoers: exact commands only, real binary paths -------------------------------------
NGINX_BIN="$(command -v nginx || echo /usr/sbin/nginx)"
SYSTEMCTL_BIN="$(command -v systemctl || echo /usr/bin/systemctl)"
CERTBOT_BIN="$(command -v certbot || echo /usr/bin/certbot)"
SYSTEMD_RUN_BIN="$(command -v systemd-run || echo /usr/bin/systemd-run)"
# One literal line per package-catalog entry, rendered from the same argv the
# install_package tool executes (bastion/tools/packages.py). No wildcards.
APT_RULES="$("${VENV}/bin/python" -m bastion.tools --sudoers-apt "${SYSTEMD_RUN_BIN}")"
SUDO_VERSION="$(sudo -V 2>/dev/null | head -n1 | awk '{print $NF}')"
if "${VENV}/bin/python" - "${SUDO_VERSION}" <<'PY'
import sys
parts = [int(p) for p in (sys.argv[1] or "0").replace("p", ".").split(".") if p.isdigit()]
sys.exit(0 if parts[:3] >= [1, 9, 10] else 1)
PY
then
  CERTBOT_RULE="${CERTBOT_BIN} ^--nginx -d [a-z0-9.-]+ --non-interactive --agree-tos -m [^ ]+\$"
else
  warn "sudo ${SUDO_VERSION:-?} lacks regex rules (< 1.9.10); using a glob for the certbot domain."
  warn "The executor validates the domain (^[a-z0-9.-]+$) before sudo is ever reached."
  CERTBOT_RULE="${CERTBOT_BIN} --nginx -d [a-z0-9.-]* --non-interactive --agree-tos -m *"
fi

TMP_SUDOERS="$(mktemp)"
cat > "${TMP_SUDOERS}" <<EOF
# /etc/sudoers.d/bastion  (generated by bastion install.sh; mode 0440)
#
# Exactly the commands Bastion's tools run, nothing else. There is deliberately
# no rule for kill, rm, bash, sh, apt-get remove/purge, or any command that
# accepts a free-form path. kill_process uses CAP_KILL from the systemd unit
# instead of sudo. BASTION_APT is generated from the package catalog.

Defaults:${BASTION_USER} !requiretty
Defaults:${BASTION_USER} env_reset
Defaults:${BASTION_USER} timestamp_timeout=0

Cmnd_Alias BASTION_NGINX     = ${NGINX_BIN} -t
Cmnd_Alias BASTION_SYSTEMCTL = ${SYSTEMCTL_BIN} restart nginx, \\
                               ${SYSTEMCTL_BIN} restart gunicorn, \\
                               ${SYSTEMCTL_BIN} restart celery, \\
                               ${SYSTEMCTL_BIN} restart postgresql
Cmnd_Alias BASTION_CERTBOT   = ${CERTBOT_BIN} renew, \\
                               ${CERTBOT_RULE}
${APT_RULES}

${BASTION_USER} ALL=(root) NOPASSWD: BASTION_NGINX, BASTION_SYSTEMCTL, BASTION_CERTBOT, BASTION_APT
EOF
visudo -cf "${TMP_SUDOERS}" >/dev/null || die "generated sudoers file failed visudo -c"
install -m 0440 -o root -g root "${TMP_SUDOERS}" "${SUDOERS}"
rm -f "${TMP_SUDOERS}"
say "installed ${SUDOERS}"

# --- systemd unit -------------------------------------------------------------------------
cat > "${UNIT}" <<'EOF'
[Unit]
Description=Bastion executor (AI SRE tool runner, loopback only)
Documentation=https://github.com/itsrajverma/bastion
After=network.target

[Service]
Type=simple
User=bastion
Group=bastion
Environment=BASTION_CONFIG=/etc/bastion/config.yaml
Environment=PYTHONUNBUFFERED=1
ExecStart=/opt/bastion/bin/bastion-executor
Restart=always
RestartSec=2
UMask=0077

# --- sandbox -----------------------------------------------------------------
# The whole filesystem is read-only except the audit log directory.
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=/var/log/bastion
# sudo keeps timestamp files here; ignored if the directory does not exist.
ReadWritePaths=-/run/sudo
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
ProtectClock=true
ProtectHostname=true
LockPersonality=true
RestrictRealtime=true
RestrictNamespaces=true
SystemCallArchitectures=native
MemoryDenyWriteExecute=true

# kill_process sends SIGTERM via os.kill after the protected-target guard, so
# the service needs CAP_KILL and no sudo rule for kill (see docs/DECISIONS.md).
AmbientCapabilities=CAP_KILL

# sudo is a setuid binary; NoNewPrivileges/RestrictSUIDSGID would break the
# systemctl/nginx/certbot/systemd-run rules in deploy/sudoers.bastion. Do not enable them.
NoNewPrivileges=false

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now bastion-executor >/dev/null
systemctl restart bastion-executor
sleep 1
systemctl is-active --quiet bastion-executor || {
  journalctl -u bastion-executor -n 20 --no-pager >&2 || true
  die "bastion-executor failed to start"
}
say "bastion-executor is running on ${BIND}"

# --- summary ------------------------------------------------------------------------------
cat <<EOF

Bastion executor installed.

  config   ${CONFIG}          (enabled_risks: [read] until you say otherwise)
  audit    ${LOG_DIR}/audit.jsonl
  service  systemctl status bastion-executor
EOF
if [[ -n "${TOKEN}" ]]; then
  cat <<EOF

  admin token (shown once; stored in ${CONFIG}):

      ${TOKEN}

EOF
else
  echo
  echo "  token: unchanged (see ${CONFIG})"
fi
cat <<'EOF'
Next steps on your laptop:

  pipx install bastion-sre
  ssh -L 8710:localhost:8710 user@this-server        # keep this open
  bastion init                                       # url http://127.0.0.1:8710 + token
  bastion doctor
  bastion ask "what's using the most CPU?"

To allow approval-gated actions, edit enabled_risks in the config
(e.g. [read, write]) and run: systemctl restart bastion-executor
To let admins install nginx/apache/php/mysql/postgresql/redis/... from the
fixed catalog, add admin as well: enabled_risks: [read, write, admin]
EOF
